### ISSUE TITLE
unicode error

### ISSUE THREAD

**Issue by initbar** [meetmangukiya/instagram-scraper#5] opened 2018-06-24 13:47 UTC
```
~/Downloads/instagram-scraper => python3 instagram_scraper.py  --tag test
[test] downloaded https://scontent-ort2-2.cdninstagram.com/vp/188d7488bf24b1ea94461e9e6881a168/5BE4C024/t51.2885-15/s150x150/e35/35155975_454524598306381_4206684960490258432_n.jpg as 0.jpg in data/test
Traceback (most recent call last):
  File "instagram_scraper.py", line 101, in <module>
    main(args.tags, args.count)
  File "instagram_scraper.py", line 89, in main
    _single_tag_processing(tag, total_count)
  File "instagram_scraper.py", line 84, in _single_tag_processing
    ', '.join(mentions)
UnicodeEncodeError: 'ascii' codec can't encode character '\u015f' in position 193: ordinal not in range(128)
```

**Comment by Suleman-Elahi** [comment] 2018-06-25 06:34
Yeah. I am getting the same on Windows 10
![image](https://user-images.githubusercontent.com/24384996/41833916-e443b604-786f-11e8-9903-13bb13120cd8.png)

**Comment by meetmangukiya** [comment] 2018-06-25 07:39
@Suleman-Elahi @initbar Does changing the `join` to `', '.join([unicode(x) for x in mentions])` work? This seems to be working fine for me.

**Comment by Suleman-Elahi** [comment] 2018-06-25 11:24
No I don't think so its working. I am getting "NameError: name 'unicode' is not defined". !!!!

**Comment by meetmangukiya** [comment] 2018-06-25 11:53
I think maybe this would work `u', '.join(mentions)`. If only I could reproduce this on my PC.

**Comment by initbar** [comment] 2018-06-25 13:30
@Suleman-Elahi @meetmangukiya true, since `unicode` (Python 2) was redefined to `str` (Python 3), I think the equivalent statement would be a `', '.join([str(x) for x in mentions])`. However, doing `str` doesn't seem to work either.

**Comment by initbar** [comment] 2018-06-25 13:30
I'll try to get a `Dockerfile` ready so that @meetmangukiya can reproduce this issue :smile:

**Comment by meetmangukiya** [comment] 2018-06-25 19:40
This was fixed by @paul-15 via https://github.com/meetmangukiya/instagram-scraper/commit/f1080ead623e385f9192c87ee3fc70ed2c9992e7 If this still persists for you guys, we can reopen this.

**Closed as completed by meetmangukiya** 2018-06-25 19:40 UTC
Labels: bug
